json_template = {"mei":
    [
        {"meihead": 
            [{"filedesc": 
                [{"titlestmt": 
                    [{"title": 
                        ["This is the title"]
                    }]
                }]
            }, 
            {"encodingdesc": 
                [{"projectdesc": 
                    [{"p": ["This file was generated by PyMEI 1.0"]}]
                }]
            }]
        },
        {"music": 
            [{"body": 
                [{"mdiv": 
                    [{"score": 
                        [{"scoredef": 
                            [   
                                {"@attributes": [["meter.count", 4], ["meter.unit", 4], ["meter.sym", "common"], ["key.sig", "4f"]]},
                                {"staffgrp": 
                                    [{"staffdef": 
                                        [
                                            {"@attributes": [["n", 1], ["xml:id", "P1"], ["label.full", "Part_1"], ["lines", 5], ["clef.line", 2], ["clef.shape", "G"], ["ppq", 2], ["key.sig", "4f"]]}, 
                                            {}
                                        ]
                                    },
                                    {"staffdef": 
                                        [
                                            {"@attributes": [["n", 1], ["xml:id", "P2"], ["label.full", "Part_2"], ["lines", 5], ["clef.line", 2], ["clef.shape", "F"], ["ppq", 2], ["key.sig", "4f"]]},
                                            {}
                                        ]
                                    }]
                                }
                            ]
                        }, {"section": 
                                [{"scoredef": 
                                    [
                                        {"@attributes": [["meter.count", 4], ["meter.unit", 4], ["meter.sym", "common"], ["key.sig", "4f"]]},
                                        {}
                                    ]
                                }, 
                                {"measure": 
                                    [
                                        {"@attributes": [["n", 1], ["xml:id", "d1e15"]]},
                                        {"staff": 
                                            [
                                                {"@attributes": [["n", 1]]},
                                                {"layer": 
                                                    [
                                                        {"@attributes": [["n", 1]]},
                                                        {"note": 
                                                            [
                                                                {"@attributes": [["xml:id", "d1e60"], ["pname", "c"], ["oct", 4], ["dur", 4], ["dur.ges", 2], ["stem.dir", "up"]]},
                                                                {}
                                                            ]
                                                        }
                                                    ]
                                                }, {"layer": 
                                                    [
                                                        {"@attributes": [["n", 2]]},
                                                        {"note": 
                                                            [
                                                                {"@attributes": [["xml:id", "d1e41"], ["pname", "c"], ["oct", 4], ["dur", 4], ["dur.ges", "2"], ["stem.dir", "down"]]},
                                                                {}
                                                            ]
                                                        }
                                                    ]
                                                }
                                            ]
                                        }, {"staff": 
                                            [
                                                {"@attributes": [["n", 2]]},
                                                {"layer": 
                                                    [
                                                        {"@attributes": [["n", 1]]},
                                                        {"rest": 
                                                            [
                                                                {"@attributes": [["xml:id", "d1e100"], ["dur", "4"], ["dur.ges", "2"]]},
                                                                {}
                                                            ]
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }]
                            }
                        ]
                    }]
                }]
            }]
        }
    ]
}