bare_template = """
{"mei":
    [
        {"meihead": 
            [{"filedesc": 
                [{"titlestmt": 
                    [{"title": 
                        ["This is the title"]
                    }]
                }]
            }, 
            {"encodingdesc": 
                [{"projectdesc": 
                    [{"p": ["This file was generated by PyMEI 1.0"]}]
                }]
            }]
        },
        {"music": 
            [{"body": 
                [{"mdiv": [] }]
            }]
        }
    ]
}"""