{"mei":
    [
        {"meihead": 
            [{"filedesc": 
                [{"titlestmt": 
                    [{"title": 
                        [{"@value": "This is the title"}]
                    }]
                }]
            }, 
            {"encodingdesc": 
                [{"projectdesc": 
                    [{"p": 
                        [
                            {"@value": "This file was generated by PyMEI 1.0 on "},
                            {"@attributes": {"foo": "bar", "baz": "bif"}},
                            {"periodname": 
                                [
                                    {"@value": "1980-01-01"},
                                    {"@tail": " with tail text"}
                                ]
                            }
                        ]
                    }]
                }]
            }]
        },
        {"music": 
            [{"body": 
                [{"mdiv": 
                    [{"score": 
                        [{"scoredef": 
                            [   
                                {"@attributes": {"meter.count": 4, "meter.unit": 4, "meter.sym": "common","key.sig": "4f"}},
                                {"staffgrp": 
                                    [{"staffdef": 
                                        [
                                            {"@attributes": {"n": 1, "xml:id": "P1", "label.full": "Part_1", "lines": 5, "clef.line": 2, "clef.shape": "G", "ppq": 2, "key.sig": "4f"}}
                                        ]
                                    },
                                    {"staffdef": 
                                        [
                                            {"@attributes": {"n": 1, "xml:id": "P1", "label.full": "Part_1", "lines": 5, "clef.line": 2, "clef.shape": "G", "ppq": 2, "key.sig": "4f"}}
                                        ]
                                    }]
                                }
                            ]
                        }, {"section": 
                                [{"scoredef": 
                                    [
                                        {"@attributes": {"meter.count": 4, "meter.unit": 4, "meter.sym": "common", "key.sig": "4f"}}
                                    ]
                                }, 
                                {"measure": 
                                    [
                                        {"@attributes": {"n": 1, "xml:id": "d1e15"}},
                                        {"staff": 
                                            [
                                                {"@attributes": {"n": 1}},
                                                {"layer": 
                                                    [
                                                        {"@attributes": {"n": 1}},
                                                        {"note": 
                                                            [
                                                                {"@attributes": {"n": 1, "xml:id": "P1", "label.full": "Part_1", "lines": 5, "clef.line": 2, "clef.shape": "G", "ppq": 2, "key.sig": "4f"}}
                                                            ]
                                                        }
                                                    ]
                                                }, {"layer": 
                                                    [
                                                        {"@attributes": {"n": 2}},
                                                        {"note": 
                                                            [
                                                                {"@attributes": {"n": 1, "xml:id": "P1", "label.full": "Part_1", "lines": 5, "clef.line": 2, "clef.shape": "G", "ppq": 2, "key.sig": "4f"}}
                                                            ]
                                                        }
                                                    ]
                                                }
                                            ]
                                        }, {"staff": 
                                            [
                                                {"@attributes": {"n": 2}},
                                                {"layer": 
                                                    [
                                                        {"@attributes": {"n": 1}},
                                                        {"rest": 
                                                            [
                                                                {"@attributes": {"xml:id": "d1e100", "dur": "4", "dur.ges": "2"}}
                                                            ]
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }]
                            }
                        ]
                    }]
                }]
            }]
        }
    ]
}